/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as PlanDuSiteRouteImport } from './routes/plan-du-site'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as ConfirmationNumeroRouteImport } from './routes/confirmation.$numero'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDuSiteRoute = PlanDuSiteRouteImport.update({
  id: '/plan-du-site',
  path: '/plan-du-site',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationNumeroRoute = ConfirmationNumeroRouteImport.update({
  id: '/confirmation/$numero',
  path: '/confirmation/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/panier': typeof PanierRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/recherche': typeof RechercheRoute
  '/services': typeof ServicesRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/confirmation/$numero': typeof ConfirmationNumeroRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/panier': typeof PanierRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/recherche': typeof RechercheRoute
  '/services': typeof ServicesRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/confirmation/$numero': typeof ConfirmationNumeroRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/panier': typeof PanierRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/recherche': typeof RechercheRoute
  '/services': typeof ServicesRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/confirmation/$numero': typeof ConfirmationNumeroRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/cgv'
    | '/commande'
    | '/confidentialite'
    | '/contact'
    | '/devis'
    | '/panier'
    | '/plan-du-site'
    | '/recherche'
    | '/services'
    | '/categorie/$slug'
    | '/confirmation/$numero'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/cgv'
    | '/commande'
    | '/confidentialite'
    | '/contact'
    | '/devis'
    | '/panier'
    | '/plan-du-site'
    | '/recherche'
    | '/services'
    | '/categorie/$slug'
    | '/confirmation/$numero'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/cgv'
    | '/commande'
    | '/confidentialite'
    | '/contact'
    | '/devis'
    | '/panier'
    | '/plan-du-site'
    | '/recherche'
    | '/services'
    | '/categorie/$slug'
    | '/confirmation/$numero'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CgvRoute: typeof CgvRoute
  CommandeRoute: typeof CommandeRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  PanierRoute: typeof PanierRoute
  PlanDuSiteRoute: typeof PlanDuSiteRoute
  RechercheRoute: typeof RechercheRoute
  ServicesRoute: typeof ServicesRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ConfirmationNumeroRoute: typeof ConfirmationNumeroRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-du-site': {
      id: '/plan-du-site'
      path: '/plan-du-site'
      fullPath: '/plan-du-site'
      preLoaderRoute: typeof PlanDuSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$numero': {
      id: '/confirmation/$numero'
      path: '/confirmation/$numero'
      fullPath: '/confirmation/$numero'
      preLoaderRoute: typeof ConfirmationNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CgvRoute: CgvRoute,
  CommandeRoute: CommandeRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  PanierRoute: PanierRoute,
  PlanDuSiteRoute: PlanDuSiteRoute,
  RechercheRoute: RechercheRoute,
  ServicesRoute: ServicesRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ConfirmationNumeroRoute: ConfirmationNumeroRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
