/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as ConfirmationNumeroRouteImport } from './routes/confirmation.$numero'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationNumeroRoute = ConfirmationNumeroRouteImport.update({
  id: '/confirmation/$numero',
  path: '/confirmation/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/devis': typeof DevisRoute
  '/panier': typeof PanierRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/confirmation/$numero': typeof ConfirmationNumeroRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/devis': typeof DevisRoute
  '/panier': typeof PanierRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/confirmation/$numero': typeof ConfirmationNumeroRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/devis': typeof DevisRoute
  '/panier': typeof PanierRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/confirmation/$numero': typeof ConfirmationNumeroRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commande'
    | '/devis'
    | '/panier'
    | '/categorie/$slug'
    | '/confirmation/$numero'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commande'
    | '/devis'
    | '/panier'
    | '/categorie/$slug'
    | '/confirmation/$numero'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/commande'
    | '/devis'
    | '/panier'
    | '/categorie/$slug'
    | '/confirmation/$numero'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandeRoute: typeof CommandeRoute
  DevisRoute: typeof DevisRoute
  PanierRoute: typeof PanierRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ConfirmationNumeroRoute: typeof ConfirmationNumeroRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$numero': {
      id: '/confirmation/$numero'
      path: '/confirmation/$numero'
      fullPath: '/confirmation/$numero'
      preLoaderRoute: typeof ConfirmationNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandeRoute: CommandeRoute,
  DevisRoute: DevisRoute,
  PanierRoute: PanierRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ConfirmationNumeroRoute: ConfirmationNumeroRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
